---
- include_tasks: java.yml

- name: Download elasticsearch
  get_url: dest=/root/elasticsearch-{{ es_version }}.deb
           url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ es_version }}.deb

- name: Install elasticsearch
  apt: deb=/root/elasticsearch-{{ es_version }}.deb state=installed
  register: elasticsearch_installed

- name: Make sure elasticsearch is running
  service: name=elasticsearch state=started enabled=yes

- name: Install elasticsearch config file
  template: dest=/etc/elasticsearch/elasticsearch.yml backup=yes
            src=elasticsearch/elasticsearch.yml
            owner=root group=root mode=0644
  register: elasticsearch_config

- name: Check whether elasticsearch javascript plugin is installed
  stat: path=/usr/share/elasticsearch/plugins/lang-javascript/
  register: es_js_plugin

- name: Install elasticsearch javascript scripting plugin
  shell: ./plugin --install elasticsearch/elasticsearch-lang-javascript/{{ es_lang_javascript_version }}
  args:
    chdir: /usr/share/elasticsearch/bin
  when: es_js_plugin.stat.exists == False

- name: Create elasticsearch scripts directory
  file: path=/etc/elasticsearch/scripts/ state=directory
        owner=root group=root mode=0755

- name: Restart elasticsearch
  service: name=elasticsearch state=restarted
  when: elasticsearch_config.changed or elasticsearch_installed.changed
