---
- name: Add postgres apt key
  apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"
           state=present

- name: Add postgres apt repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
                  state=present update_cache=yes

- name: Install PostgreSQL and PostGIS system packages
  apt:
    state: present
    name:
    - postgresql-13-postgis-3
    - postgresql-server-dev-13
    - gdal-bin
    - libproj-dev
    - libpq-dev
    - libgeoip1
    - python-psycopg2 # Needed for Ansible provisioning

- name: Install psycopg2 for other ansible tasks
  command: "python3 -m pip install psycopg2==2.8.6"

- name: Make sure postgresql is running
  service: name=postgresql state=started enabled=yes

- name: Install postgresql config file
  template: src="postgresql/pg_hba.conf" backup=yes
            dest="/etc/postgresql/13/main/pg_hba.conf"
            owner=postgres group=postgres mode=0640
  register: postgresql_config

- name: Create backup directoy
  file: name=/var/lib/postgresql/backups/ state=directory
        owner=postgres group=postgres mode=0755

- name: Reload postgresql
  service: name=postgresql state=reloaded
  when: postgresql_config.changed
