---
- name: Add redis apt repository
  apt_repository: repo="ppa:chris-lea/redis-server"

- name: Install redis
  apt: name=redis-server state=present

- name: Make sure redis is running
  service: name=redis-server state=started
