---
- block:
  - name: Set up site directory structure
    file: path="/var/www/{{ site_name }}/{{ site_name}}/" state=directory
          owner={{ deploy_user }} group={{ deploy_user }}

  - name: Install git
    apt: name=git-core state=present

  - name: Allow access to git servers without SSH prompt
    lineinfile:
      path: "/home/{{ deploy_user }}/.ssh/known_hosts"
      create: yes
      line: "{{ github_host_key }}"

  - name: Clone repo
    git:
      repo: "{{ repo_url }}"
      dest: "/var/www/{{ site_name }}/{{ site_name}}/"
  when: env != "development"


- include_tasks: system-setup.yml
- include_tasks: python.yml
- include_tasks: unattended-upgrades.yml
  when: env != "development"
