---
- name: Install python system packages
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools

- name: Install pip with easy_install
  easy_install: name=pip

- name: Install system python packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: virtualenv
      version: 13.1.2

    - name: virtualenvwrapper
      version: 4.7.0

    - name: pip
      version: 7.1.2

    - name: pip-tools
      version: 1.1.4

    - name: mercurial
      version: 3.5
