---
- name: Install python system packages
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools

- name: Install pip with easy_install
  easy_install: name=pip

- name: Install system python packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: virtualenv
      version: 15.1.0
    - name: virtualenvwrapper
      version: 4.7.2
    - name: pip
      version: 9.0.1
    - name: pip-review
      version: 0.5.2

- name: Set up pdb++ defaults
  template: src=pdbrc.py dest=/home/{{ ansible_ssh_user }}/.pdbrc.py
            owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=664
