---
- name: Install python system packages
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools

- name: Install pip with easy_install
  easy_install: name=pip

- name: Install system python packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: virtualenv
      version: 15.0.3
    - name: virtualenvwrapper
      version: 4.7.1
    - name: pip
      version: 9.0.0
    - name: pip-review
      version: 0.5
    - name: mercurial
      version: 4.0.0
