---
- name: Add python apt repository
  apt_repository: repo="ppa:deadsnakes/ppa"
                  state=present update_cache=yes

- name: Install python system packages
  apt:
    state: present
    name:
      - python3.8
      - python3.8-dev
      - python3.8-distutils

- name: Install pip for python3.8
  shell: "curl https://bootstrap.pypa.io/get-pip.py | sudo python3.8"

- name: Install pip for system python
  apt: name=python3-pip

- name: Install system python packages
  shell: /usr/local/bin/pip install {{ item.name }}=={{ item.version }}
  with_items:
    - name: virtualenv
      version: 20.0.33
    - name: virtualenvwrapper
      version: 4.8.4
    - name: pip
      version: 20.3.3

- name: Set up pdb++ defaults
  template: src=pdbrc.py dest=/home/{{ ansible_ssh_user }}/.pdbrc.py
            owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=664
