---
- name: Add python apt repository
  apt_repository: repo="ppa:deadsnakes/ppa"
                  state=present update_cache=yes

- name: Install python system packages
  apt: name={{ item }} state=present
  with_items:
    - python3.7
    - python3.7-dev

- name: Install pip for python3.7
  shell: "curl https://bootstrap.pypa.io/get-pip.py | sudo python3.7"

- name: Install system python packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: virtualenv
      version: 16.0.0
    - name: virtualenvwrapper
      version: 4.8.2
    - name: pip
      version: 18.0

- name: Set up pdb++ defaults
  template: src=pdbrc.py dest=/home/{{ ansible_ssh_user }}/.pdbrc.py
            owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=664
