---
- name: Set hostname
  hostname: name={{ hostname }}

- name: Install system packages
  apt: name={{ item }} state=present
  with_items:
    # General
    - bash-completion
    - git
    - ntp
    # Build
    - build-essential
    - binutils-doc
    - autoconf
    - flex
    - bison
    # Utility
    - htop
    - tig
    - tmux
    - vim

- name: Create deploy user
  user: name={{ user }} shell=/bin/bash

- name: Add public key to the server
  authorized_key: user={{ user }}
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Install shell config files
  template: src={{ item }} dest=/home/{{ user }}/.{{ item }}
            owner={{ user }} group={{ user }} mode=0755
  with_items:
    - bashrc
    - vimrc
    - django_bash_completion